USE master
GO
IF EXISTS( SELECT * FROM sysdatabases WHERE NAME='MCDONALDS')
	DROP DATABASE MCDONALDS
GO
CREATE DATABASE MCDONALDS
GO
USE MCDONALDS
GO
CREATE TABLE NHANVIEN(
	ID NVARCHAR(12) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE,
	HINHTHUC NVARCHAR(8) NOT NULL
)
GO
