USE master
GO
IF EXISTS( SELECT * FROM sysdatabases WHERE NAME='MCDONALDS')
	DROP DATABASE MCDONALDS
GO
CREATE DATABASE MCDONALDS
GO
USE MCDONALDS
GO
--BẢNG CHO LIÊN QUAN ĐẾN ĐẶT MÓN
CREATE TABLE TAIKHOANKH(
	IDKH VARCHAR(12),
	SDT VARCHAR(10) NOT NULL,
	EMAIL NVARCHAR(50),
	PASSWORD VARCHAR(18) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	THUHANG INT,
	PRIMARY KEY(IDKH)
)
GO

CREATE TABLE VOUCHER(
	IDVOUCHER VARCHAR(12),
	SOTIENGIAM INT NOT NULL,
	TGBATDAU DATETIME NOT NULL,
	TGKETTHUC DATETIME,
	DONVI NVARCHAR(3) NOT NULL,
	DK INT NOT NULL,
	TOIDA INT NOT NULL,
	PRIMARY KEY(IDVOUCHER)
)
GO

CREATE TABLE SOHUU(
	IDKH VARCHAR(12),
	IDVOUCHER VARCHAR(12),
	SOLANSD INT,
	PRIMARY KEY(IDKH, IDVOUCHER),
	FOREIGN KEY(IDKH) REFERENCES TAIKHOANKH(IDKH),
	FOREIGN KEY(IDVOUCHER) REFERENCES VOUCHER(IDVOUCHER)
)
GO

CREATE TABLE HOADON(
	IDHD VARCHAR(9),
	THOIGIANLAP DATETIME NOT NULL,
	TONGTIEN INT NOT NULL,
	SOBOT INT NOT NULL,
	STT INT NOT NULL,
	GIAGOC INT NOT NULL,
	IDKH VARCHAR(12),
	IDVOUCHER VARCHAR(12),
	PRIMARY KEY(IDHD),
	FOREIGN KEY(IDKH) REFERENCES TAIKHOANKH(IDKH),
	FOREIGN KEY(IDVOUCHER) REFERENCES VOUCHER(IDVOUCHER)
)
GO

CREATE TABLE COMBO(
	IDCOMBO VARCHAR(9),
	GIACOMBO INT NOT NULL,
	TENCB NVARCHAR(50) NOT NULL,
	TRANGTHAI NVARCHAR(10),
	PRIMARY KEY(IDCOMBO)
)
GO

CREATE TABLE HDCOMBO(
	IDHD VARCHAR(9),
	IDCOMBO VARCHAR(9),
	SOLUONG FLOAT,
	PRIMARY KEY(IDHD, IDCOMBO),
	FOREIGN KEY(IDHD) REFERENCES HOADON(IDHD),
	FOREIGN KEY(IDCOMBO) REFERENCES COMBO(IDCOMBO)
)
GO

CREATE TABLE MON(
	IDMON VARCHAR(9),
	TENMON NVARCHAR(50) NOT NULL,
	GIAMON INT NOT NULL,
	TRANGTHAI NVARCHAR(10),
	PRIMARY KEY(IDMON)
)
GO

CREATE TABLE HDMON(
	IDHD VARCHAR(9),
	IDMON VARCHAR(9),
	SOLUONG FLOAT,
	PRIMARY KEY(IDHD, IDMON),
	FOREIGN KEY(IDHD) REFERENCES HOADON(IDHD),
	FOREIGN KEY(IDMON) REFERENCES MON(IDMON)
)
GO

CREATE TABLE CTMON(
	IDCTMON VARCHAR(12),
	TIENTHEM INT NOT NULL,
	TRANGTHAI NVARCHAR(10),
	TENCTM NVARCHAR(50) NOT NULL,
	IDMON VARCHAR(9),
	PRIMARY KEY(IDCTMON),
	FOREIGN KEY(IDMON) REFERENCES MON(IDMON)
)
GO

CREATE TABLE HDCTMON(
	IDHD VARCHAR(9),
	IDCTMON VARCHAR(12),
	SOLUONG FLOAT,
	PRIMARY KEY(IDHD, IDCTMON),
	FOREIGN KEY(IDHD) REFERENCES HOADON(IDHD),
	FOREIGN KEY(IDCTMON) REFERENCES CTMON(IDCTMON)
)
GO

CREATE TABLE CTCOMBO(
	IDCOMBO VARCHAR(9),
	IDCTMON VARCHAR(12),
	SOLUONG FLOAT,
	PRIMARY KEY(IDCOMBO, IDCTMON),
	FOREIGN KEY(IDCOMBO) REFERENCES COMBO(IDCOMBO),
	FOREIGN KEY(IDCTMON) REFERENCES CTMON(IDCTMON)
)
GO

CREATE TABLE GIAMGIACB(
	IDGGCOMBO VARCHAR(12),
	GIABAN INT NOT NULL,
	TGBATDAU DATETIME NOT NULL,
	TGKETTHUC DATETIME,
	IDCOMBO VARCHAR(9),
	PRIMARY KEY(IDGGCOMBO),
	FOREIGN KEY(IDCOMBO) REFERENCES COMBO(IDCOMBO)
)
GO

CREATE TABLE GIAMGIAMON(
	IDGGMON VARCHAR(12),
	GIABAN INT NOT NULL,
	TGBATDAU DATETIME NOT NULL,
	TGKETTHUC DATETIME,
	IDMON VARCHAR(9),
	PRIMARY KEY(IDGGMON),
	FOREIGN KEY(IDMON) REFERENCES MON(IDMON)
)
GO

--BẢNG CHO NHÂN VIÊN VÀ TÀI KHOẢN
CREATE TABLE NHANVIEN(
	IDNV VARCHAR(9),
	HOTEN NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50),
	SDT VARCHAR(10) NOT NULL,
	PHANLOAINV NVARCHAR(10) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	CHUCVU NVARCHAR(10) NOT NULL,
	PASSWORD VARCHAR(18),
	PRIMARY KEY(IDNV)
)
GO

CREATE TABLE TAIKHOAN(
	USERNAME VARCHAR(18),
	PASSWORD VARCHAR(18) NOT NULL,
	CHUCVU NVARCHAR(10) NOT NULL,
	PRIMARY KEY(USERNAME)
)
GO

--BẢNG CHO QUẢN LÝ KHO
CREATE TABLE NGUYENLIEU(
	IDNL VARCHAR(9),
	TENNL NVARCHAR(50) NOT NULL,
	DONVI NVARCHAR(3) NOT NULL,
	PRIMARY KEY(IDNL)
)
GO

CREATE TABLE NHAPHANG(
	IDNH VARCHAR(9),
	THOIGIANNHAP DATETIME NOT NULL,
	NCC NVARCHAR(50) NOT NULL,
	PRIMARY KEY(IDNH)
)
GO

CREATE TABLE LOHANG(
	IDLH VARCHAR(9),
	SOLUONG FLOAT NOT NULL,
	HANSD DATETIME NOT NULL,
	IDNL VARCHAR(9),
	IDNH VARCHAR(9),
	PRIMARY KEY(IDLH),
	FOREIGN KEY(IDNL) REFERENCES NGUYENLIEU(IDNL),
	FOREIGN KEY(IDNH) REFERENCES NHAPHANG(IDNH)
)
GO

CREATE TABLE KHO(
	IDKT VARCHAR(12),
	TGKIEMTRA DATETIME NOT NULL,
	SOLUONG FLOAT NOT NULL,
	IDLH VARCHAR(9),
	PRIMARY KEY(IDKT),
	FOREIGN KEY(IDLH) REFERENCES LOHANG(IDLH)
)
